// Données géographiques de l'Algérie — 58 wilayas + communes
// Source : dataset open-source des communes algériennes
// Utilisé dans le checkout pour la cascade wilaya → communes

export interface Wilaya {
  code: string // ex: "16" pour Alger
  nameAr: string
  nameFr: string
}

export interface Commune {
  wilayaCode: string
  nameAr: string
  nameFr: string
}

// 58 wilayas (incluant les 10 nouvelles créées en 2019)
export const WILAYAS: Wilaya[] = [
  { code: '01', nameAr: 'أدرار', nameFr: 'Adrar' },
  { code: '02', nameAr: 'الشلف', nameFr: 'Chlef' },
  { code: '03', nameAr: 'الأغواط', nameFr: 'Laghouat' },
  { code: '04', nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi' },
  { code: '05', nameAr: 'باتنة', nameFr: 'Batna' },
  { code: '06', nameAr: 'بجاية', nameFr: 'Béjaïa' },
  { code: '07', nameAr: 'بسكرة', nameFr: 'Biskra' },
  { code: '08', nameAr: 'بشار', nameFr: 'Béchar' },
  { code: '09', nameAr: 'البليدة', nameFr: 'Blida' },
  { code: '10', nameAr: 'البويرة', nameFr: 'Bouira' },
  { code: '11', nameAr: 'تمنراست', nameFr: 'Tamanrasset' },
  { code: '12', nameAr: 'تبسة', nameFr: 'Tébessa' },
  { code: '13', nameAr: 'تلمسان', nameFr: 'Tlemcen' },
  { code: '14', nameAr: 'تيارت', nameFr: 'Tiaret' },
  { code: '15', nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou' },
  { code: '16', nameAr: 'الجزائر', nameFr: 'Alger' },
  { code: '17', nameAr: 'الجلفة', nameFr: 'Djelfa' },
  { code: '18', nameAr: 'جيجل', nameFr: 'Jijel' },
  { code: '19', nameAr: 'سطيف', nameFr: 'Sétif' },
  { code: '20', nameAr: 'سعيدة', nameFr: 'Saïda' },
  { code: '21', nameAr: 'سكيكدة', nameFr: 'Skikda' },
  { code: '22', nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel Abbès' },
  { code: '23', nameAr: 'عنابة', nameFr: 'Annaba' },
  { code: '24', nameAr: 'قالمة', nameFr: 'Guelma' },
  { code: '25', nameAr: 'قسنطينة', nameFr: 'Constantine' },
  { code: '26', nameAr: 'المدية', nameFr: 'Médéa' },
  { code: '27', nameAr: 'مستغانم', nameFr: 'Mostaganem' },
  { code: '28', nameAr: 'المسيلة', nameFr: 'M\'Sila' },
  { code: '29', nameAr: 'معسكر', nameFr: 'Mascara' },
  { code: '30', nameAr: 'ورقلة', nameFr: 'Ouargla' },
  { code: '31', nameAr: 'وهران', nameFr: 'Oran' },
  { code: '32', nameAr: 'البيض', nameFr: 'El Bayadh' },
  { code: '33', nameAr: 'إليزي', nameFr: 'Illizi' },
  { code: '34', nameAr: 'برج بوعريريج', nameFr: 'Bordj Bou Arréridj' },
  { code: '35', nameAr: 'بومرداس', nameFr: 'Boumerdès' },
  { code: '36', nameAr: 'الطارف', nameFr: 'El Tarf' },
  { code: '37', nameAr: 'تندوف', nameFr: 'Tindouf' },
  { code: '38', nameAr: 'تيسمسيلت', nameFr: 'Tissemsilt' },
  { code: '39', nameAr: 'الوادي', nameFr: 'El Oued' },
  { code: '40', nameAr: 'خنشلة', nameFr: 'Khenchela' },
  { code: '41', nameAr: 'سوق أهراس', nameFr: 'Souk Ahras' },
  { code: '42', nameAr: 'تيبازة', nameFr: 'Tipaza' },
  { code: '43', nameAr: 'ميلة', nameFr: 'Mila' },
  { code: '44', nameAr: 'عين الدفلى', nameFr: 'Aïn Defla' },
  { code: '45', nameAr: 'النعامة', nameFr: 'Naâma' },
  { code: '46', nameAr: 'عين تموشنت', nameFr: 'Aïn Témouchent' },
  { code: '47', nameAr: 'غرداية', nameFr: 'Ghardaïa' },
  { code: '48', nameAr: 'غليزان', nameFr: 'Relizane' },
  // 10 nouvelles wilayas (2019)
  { code: '49', nameAr: 'تيميمون', nameFr: 'Timimoun' },
  { code: '50', nameAr: 'برج باجي مختار', nameFr: 'Bordj Badji Mokhtar' },
  { code: '51', nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal' },
  { code: '52', nameAr: 'بني عباس', nameFr: 'Béni Abbès' },
  { code: '53', nameAr: 'عين صالح', nameFr: 'In Salah' },
  { code: '54', nameAr: 'عين قزام', nameFr: 'In Guezzam' },
  { code: '55', nameAr: 'تقرت', nameFr: 'Touggourt' },
  { code: '56', nameAr: 'جانت', nameFr: 'Djanet' },
  { code: '57', nameAr: 'المغير', nameFr: 'El M\'Ghair' },
  { code: '58', nameAr: 'المنيعة', nameFr: 'El Meniaa' },
]

// Communes complètes — toutes les 58 wilayas
export const COMMUNES: Commune[] = [
  // ── 01 Adrar ──────────────────────────────────────────────────────
  { wilayaCode: '01', nameAr: 'أدرار', nameFr: 'Adrar' },
  { wilayaCode: '01', nameAr: 'رقان', nameFr: 'Reggane' },
  { wilayaCode: '01', nameAr: 'أولاف', nameFr: 'Aoulef' },
  { wilayaCode: '01', nameAr: 'تيت', nameFr: 'Tit' },
  { wilayaCode: '01', nameAr: 'بودة', nameFr: 'Bouda' },
  { wilayaCode: '01', nameAr: 'فنوغيل', nameFr: 'Fenoughil' },
  { wilayaCode: '01', nameAr: 'أكبلي', nameFr: 'Akabli' },
  { wilayaCode: '01', nameAr: 'تسابيت', nameFr: 'Tsabit' },
  { wilayaCode: '01', nameAr: 'أنزجمير', nameFr: 'Anzejmir' },
  { wilayaCode: '01', nameAr: 'سبعة', nameFr: 'Sali' },
  { wilayaCode: '01', nameAr: 'المطرح', nameFr: 'Metarfa' },
  { wilayaCode: '01', nameAr: 'تيمسوين', nameFr: 'Timokten' },
  // ── 02 Chlef ──────────────────────────────────────────────────────
  { wilayaCode: '02', nameAr: 'الشلف', nameFr: 'Chlef' },
  { wilayaCode: '02', nameAr: 'تنس', nameFr: 'Ténès' },
  { wilayaCode: '02', nameAr: 'أم الدروع', nameFr: 'Oum Drou' },
  { wilayaCode: '02', nameAr: 'أبو الحسن', nameFr: 'Abou El Hassan' },
  { wilayaCode: '02', nameAr: 'بني حواء', nameFr: 'Béni Haoua' },
  { wilayaCode: '02', nameAr: 'الشطية', nameFr: 'Echattia' },
  { wilayaCode: '02', nameAr: 'سيدي عكاشة', nameFr: 'Sidi Akkacha' },
  { wilayaCode: '02', nameAr: 'الهرندة', nameFr: 'Hrenda' },
  { wilayaCode: '02', nameAr: 'وادي الفضة', nameFr: 'Oued Fodda' },
  { wilayaCode: '02', nameAr: 'ابن بريهمات', nameFr: 'Ibn Badis' },
  { wilayaCode: '02', nameAr: 'الكريمية', nameFr: 'Laremnia' },
  { wilayaCode: '02', nameAr: 'بوقدير', nameFr: 'Boukadir' },
  { wilayaCode: '02', nameAr: 'مصدق', nameFr: 'Medjadja' },
  { wilayaCode: '02', nameAr: 'حرشون', nameFr: 'Harenfa' },
  { wilayaCode: '02', nameAr: 'الخطاطبة', nameFr: 'El Karimia' },
  { wilayaCode: '02', nameAr: 'وادي سلي', nameFr: 'Oued Sly' },
  { wilayaCode: '02', nameAr: 'بنايرية', nameFr: 'Benairia' },
  { wilayaCode: '02', nameAr: 'الأسنام', nameFr: 'Breira' },
  // ── 03 Laghouat ───────────────────────────────────────────────────
  { wilayaCode: '03', nameAr: 'الأغواط', nameFr: 'Laghouat' },
  { wilayaCode: '03', nameAr: 'حاسي الرمل', nameFr: 'Hassi R\'Mel' },
  { wilayaCode: '03', nameAr: 'عين ماضي', nameFr: 'Aïn Madhi' },
  { wilayaCode: '03', nameAr: 'قصر الحيران', nameFr: 'Ksar El Hirane' },
  { wilayaCode: '03', nameAr: 'سيدي مخلوف', nameFr: 'Sidi Makhlouf' },
  { wilayaCode: '03', nameAr: 'آفلو', nameFr: 'Aflou' },
  { wilayaCode: '03', nameAr: 'برج خنيفيس', nameFr: 'Brida' },
  { wilayaCode: '03', nameAr: 'العسافية', nameFr: 'El Assafia' },
  { wilayaCode: '03', nameAr: 'غيلاسة', nameFr: 'Gueltat Sidi Saad' },
  { wilayaCode: '03', nameAr: 'بريدة', nameFr: 'Oued Morra' },
  { wilayaCode: '03', nameAr: 'عين سيدي علي', nameFr: 'Aïn Sidi Ali' },
  { wilayaCode: '03', nameAr: 'قلتة سيدي سعد', nameFr: 'Tadjemout' },
  { wilayaCode: '03', nameAr: 'تاجموت', nameFr: 'Oued Touil' },
  { wilayaCode: '03', nameAr: 'السبعة', nameFr: 'Sebaa' },
  { wilayaCode: '03', nameAr: 'حاسي دلاعة', nameFr: 'Hassi Delaa' },
  // ── 04 Oum El Bouaghi ─────────────────────────────────────────────
  { wilayaCode: '04', nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi' },
  { wilayaCode: '04', nameAr: 'عين البيضاء', nameFr: 'Aïn Beida' },
  { wilayaCode: '04', nameAr: 'عين مليلة', nameFr: 'Aïn M\'Lila' },
  { wilayaCode: '04', nameAr: 'عين الدياب', nameFr: 'Aïn Diyab' },
  { wilayaCode: '04', nameAr: 'فكيرينة', nameFr: 'Fkirina' },
  { wilayaCode: '04', nameAr: 'خيران', nameFr: 'Kherrana' },
  { wilayaCode: '04', nameAr: 'المسكيانة', nameFr: 'Meskiana' },
  { wilayaCode: '04', nameAr: 'الزرق', nameFr: 'El Fedjoudj' },
  { wilayaCode: '04', nameAr: 'عين الغيت', nameFr: 'Aïn El Fakhar' },
  { wilayaCode: '04', nameAr: 'سيقوس', nameFr: 'Sigus' },
  { wilayaCode: '04', nameAr: 'قصبة الرحيل', nameFr: 'Ain Zitoun' },
  { wilayaCode: '04', nameAr: 'عين كشير', nameFr: 'Aïn Kercha' },
  { wilayaCode: '04', nameAr: 'هنشير تومغني', nameFr: 'Bir Chouhada' },
  { wilayaCode: '04', nameAr: 'عين الزيتون', nameFr: 'Rahia' },
  { wilayaCode: '04', nameAr: 'الرحية', nameFr: 'Souk Naamane' },
  // ── 05 Batna ──────────────────────────────────────────────────────
  { wilayaCode: '05', nameAr: 'باتنة', nameFr: 'Batna' },
  { wilayaCode: '05', nameAr: 'مروانة', nameFr: 'Marouana' },
  { wilayaCode: '05', nameAr: 'عين توتة', nameFr: 'Aïn Touta' },
  { wilayaCode: '05', nameAr: 'آريس', nameFr: 'Arris' },
  { wilayaCode: '05', nameAr: 'بريكة', nameFr: 'Barika' },
  { wilayaCode: '05', nameAr: 'ثنية العابد', nameFr: 'Theniet El Abed' },
  { wilayaCode: '05', nameAr: 'نقاوس', nameFr: 'Ngaous' },
  { wilayaCode: '05', nameAr: 'عين جاسر', nameFr: 'Aïn Djaser' },
  { wilayaCode: '05', nameAr: 'تيمقاد', nameFr: 'Timgad' },
  { wilayaCode: '05', nameAr: 'سريانة', nameFr: 'Seriana' },
  { wilayaCode: '05', nameAr: 'بوزينة', nameFr: 'Bouzina' },
  { wilayaCode: '05', nameAr: 'حيدوسة', nameFr: 'Hidoussa' },
  { wilayaCode: '05', nameAr: 'كيمل', nameFr: 'Kimmel' },
  { wilayaCode: '05', nameAr: 'بومية', nameFr: 'Boumia' },
  { wilayaCode: '05', nameAr: 'منعة', nameFr: 'Menaa' },
  { wilayaCode: '05', nameAr: 'الشمرة', nameFr: 'Chemora' },
  { wilayaCode: '05', nameAr: 'تازولت', nameFr: 'Tazoult' },
  { wilayaCode: '05', nameAr: 'بني فضالة', nameFr: 'Beni Foudhala' },
  { wilayaCode: '05', nameAr: 'إشمول', nameFr: 'Ichmoul' },
  { wilayaCode: '05', nameAr: 'الجزار', nameFr: 'Djezzar' },
  { wilayaCode: '05', nameAr: 'تكوت', nameFr: 'Tkout' },
  { wilayaCode: '05', nameAr: 'أولاد سلام', nameFr: 'Ouled Selam' },
  { wilayaCode: '05', nameAr: 'رأس العيون', nameFr: 'Ras El Aioun' },
  // ── 06 Béjaïa ─────────────────────────────────────────────────────
  { wilayaCode: '06', nameAr: 'بجاية', nameFr: 'Béjaïa' },
  { wilayaCode: '06', nameAr: 'أقبو', nameFr: 'Akbou' },
  { wilayaCode: '06', nameAr: 'الصومام', nameFr: 'Soummam' },
  { wilayaCode: '06', nameAr: 'تيشي', nameFr: 'Tichy' },
  { wilayaCode: '06', nameAr: 'ببشر', nameFr: 'Bibeche' },
  { wilayaCode: '06', nameAr: 'أميزور', nameFr: 'Amizour' },
  { wilayaCode: '06', nameAr: 'الفلاي', nameFr: 'El Flaye' },
  { wilayaCode: '06', nameAr: 'تيغلت', nameFr: 'Tigilt' },
  { wilayaCode: '06', nameAr: 'سيدي عيش', nameFr: 'Sidi Aich' },
  { wilayaCode: '06', nameAr: 'مقلع', nameFr: 'Melbou' },
  { wilayaCode: '06', nameAr: 'خراطة', nameFr: 'Kherrata' },
  { wilayaCode: '06', nameAr: 'الكسور', nameFr: 'Leflaye' },
  { wilayaCode: '06', nameAr: 'الشرفة', nameFr: 'Cherfa' },
  { wilayaCode: '06', nameAr: 'برج منايل', nameFr: 'Bordj Menaiel' },
  { wilayaCode: '06', nameAr: 'طيبان', nameFr: 'Toudja' },
  { wilayaCode: '06', nameAr: 'سمير', nameFr: 'Souk El Tenine' },
  { wilayaCode: '06', nameAr: 'الديرة', nameFr: 'Darguina' },
  { wilayaCode: '06', nameAr: 'بني منصور', nameFr: 'Beni Maouche' },
  { wilayaCode: '06', nameAr: 'داقموس', nameFr: 'Aokas' },
  { wilayaCode: '06', nameAr: 'أوقاس', nameFr: 'Fenaia Ilmaten' },
  { wilayaCode: '06', nameAr: 'تيفرة', nameFr: 'Tichy' },
  // ── 07 Biskra ─────────────────────────────────────────────────────
  { wilayaCode: '07', nameAr: 'بسكرة', nameFr: 'Biskra' },
  { wilayaCode: '07', nameAr: 'طولقة', nameFr: 'Tolga' },
  { wilayaCode: '07', nameAr: 'سيدي عقبة', nameFr: 'Sidi Okba' },
  { wilayaCode: '07', nameAr: 'الحاجب', nameFr: 'El Hadjeb' },
  { wilayaCode: '07', nameAr: 'أوماش', nameFr: 'Oumache' },
  { wilayaCode: '07', nameAr: 'زريبة الوادي', nameFr: 'Zeribet El Oued' },
  { wilayaCode: '07', nameAr: 'الغروس', nameFr: 'El Ghrous' },
  { wilayaCode: '07', nameAr: 'مخادمة', nameFr: 'Mekhadma' },
  { wilayaCode: '07', nameAr: 'الفيض', nameFr: 'El Feidh' },
  { wilayaCode: '07', nameAr: 'ليشانة الوطاية', nameFr: 'Lichana' },
  { wilayaCode: '07', nameAr: 'جمورة', nameFr: 'Djamoura' },
  { wilayaCode: '07', nameAr: 'لوطاية', nameFr: 'Loutaya' },
  { wilayaCode: '07', nameAr: 'شتمة', nameFr: 'Chetma' },
  { wilayaCode: '07', nameAr: 'برانيس', nameFr: 'Branis' },
  { wilayaCode: '07', nameAr: 'القنطرة', nameFr: 'El Kantara' },
  { wilayaCode: '07', nameAr: 'مشونش', nameFr: 'Mechouneche' },
  { wilayaCode: '07', nameAr: 'الحوش', nameFr: 'El Houch' },
  { wilayaCode: '07', nameAr: 'أولاد الرابح', nameFr: 'Ouled Rabah' },
  { wilayaCode: '07', nameAr: 'عين ناقة', nameFr: 'Aïn Naga' },
  { wilayaCode: '07', nameAr: 'بسباس', nameFr: 'Besbes' },
  // ── 08 Béchar ─────────────────────────────────────────────────────
  { wilayaCode: '08', nameAr: 'بشار', nameFr: 'Béchar' },
  { wilayaCode: '08', nameAr: 'العبادلة', nameFr: 'Abadla' },
  { wilayaCode: '08', nameAr: 'موغل', nameFr: 'Moughel' },
  { wilayaCode: '08', nameAr: 'تبلبالة', nameFr: 'Tabelbala' },
  { wilayaCode: '08', nameAr: 'كنادسة', nameFr: 'Kenadsa' },
  { wilayaCode: '08', nameAr: 'مشرية', nameFr: 'Mecheria' },
  { wilayaCode: '08', nameAr: 'ضاية بن ضحوة', nameFr: 'Lahmar' },
  { wilayaCode: '08', nameAr: 'بوكايس', nameFr: 'Boukais' },
  { wilayaCode: '08', nameAr: 'بني ونيف', nameFr: 'Beni Ounif' },
  { wilayaCode: '08', nameAr: 'مريجة', nameFr: 'Meridja' },
  { wilayaCode: '08', nameAr: 'لحمر', nameFr: 'Lahmar' },
  { wilayaCode: '08', nameAr: 'عرق الكراريف', nameFr: 'Erg Ferradj' },
  // ── 09 Blida ──────────────────────────────────────────────────────
  { wilayaCode: '09', nameAr: 'البليدة', nameFr: 'Blida' },
  { wilayaCode: '09', nameAr: 'بوفاريك', nameFr: 'Boufarik' },
  { wilayaCode: '09', nameAr: 'الأربعاء', nameFr: 'Larbaâ' },
  { wilayaCode: '09', nameAr: 'بني مراد', nameFr: 'Beni Mered' },
  { wilayaCode: '09', nameAr: 'الشفة', nameFr: 'Chiffa' },
  { wilayaCode: '09', nameAr: 'المفتاح', nameFr: 'Meftah' },
  { wilayaCode: '09', nameAr: 'موزاية', nameFr: 'Mouzaia' },
  { wilayaCode: '09', nameAr: 'بني تامو', nameFr: 'Beni Tamou' },
  { wilayaCode: '09', nameAr: 'العفرون', nameFr: 'El Affroun' },
  { wilayaCode: '09', nameAr: 'بوعرفة', nameFr: 'Bouarfa' },
  { wilayaCode: '09', nameAr: 'خميس الخشنة', nameFr: 'Khemis El Khechna' },
  { wilayaCode: '09', nameAr: 'شبلي', nameFr: 'Chebli' },
  { wilayaCode: '09', nameAr: 'أولاد يعيش', nameFr: 'Ouled Yaich' },
  { wilayaCode: '09', nameAr: 'حمام ملوان', nameFr: 'Hammam Melouane' },
  { wilayaCode: '09', nameAr: 'واد الدوس', nameFr: 'Oued Djer' },
  { wilayaCode: '09', nameAr: 'سيدي الأخضر', nameFr: 'Souhane' },
  { wilayaCode: '09', nameAr: 'القليعة', nameFr: 'Larbaa' },
  { wilayaCode: '09', nameAr: 'بوجنان', nameFr: 'Bouinan' },
  { wilayaCode: '09', nameAr: 'الرحاحلية', nameFr: 'Rahala' },
  { wilayaCode: '09', nameAr: 'بن عمر', nameFr: 'Ben Khelil' },
  // ── 10 Bouira ─────────────────────────────────────────────────────
  { wilayaCode: '10', nameAr: 'البويرة', nameFr: 'Bouira' },
  { wilayaCode: '10', nameAr: 'عين بسام', nameFr: 'Aïn Bessam' },
  { wilayaCode: '10', nameAr: 'سور الغزلان', nameFr: 'Sour El Ghozlane' },
  { wilayaCode: '10', nameAr: 'المعاضيد', nameFr: 'El Maaadi' },
  { wilayaCode: '10', nameAr: 'الأخضرية', nameFr: 'El Akhdheria' },
  { wilayaCode: '10', nameAr: 'الحجرة', nameFr: 'Hadjera' },
  { wilayaCode: '10', nameAr: 'آث منصور', nameFr: 'Aïth Mansour' },
  { wilayaCode: '10', nameAr: 'مزدور', nameFr: 'Mazer' },
  { wilayaCode: '10', nameAr: 'حيزر', nameFr: 'Haizer' },
  { wilayaCode: '10', nameAr: 'دراع القايد', nameFr: 'Dechmia' },
  { wilayaCode: '10', nameAr: 'قدرة', nameFr: 'Kadiria' },
  { wilayaCode: '10', nameAr: 'ميزرانة', nameFr: 'Mezdour' },
  { wilayaCode: '10', nameAr: 'الأسنام', nameFr: 'Bordj Okhris' },
  { wilayaCode: '10', nameAr: 'قوقة', nameFr: 'Djebahia' },
  { wilayaCode: '10', nameAr: 'روابح', nameFr: 'Saharidj' },
  { wilayaCode: '10', nameAr: 'عين الحجل', nameFr: 'Taghzout' },
  // ── 11 Tamanrasset ────────────────────────────────────────────────
  { wilayaCode: '11', nameAr: 'تمنراست', nameFr: 'Tamanrasset' },
  { wilayaCode: '11', nameAr: 'أبالسة', nameFr: 'Abalessa' },
  { wilayaCode: '11', nameAr: 'ين أزل', nameFr: 'In Azal' },
  { wilayaCode: '11', nameAr: 'تين زاواتين', nameFr: 'Tin Zaouatine' },
  { wilayaCode: '11', nameAr: 'إيدلس', nameFr: 'Ideles' },
  // ── 12 Tébessa ────────────────────────────────────────────────────
  { wilayaCode: '12', nameAr: 'تبسة', nameFr: 'Tébessa' },
  { wilayaCode: '12', nameAr: 'بئر العاتر', nameFr: 'Bir El Ater' },
  { wilayaCode: '12', nameAr: 'الشريعة', nameFr: 'Cheria' },
  { wilayaCode: '12', nameAr: 'العوينات', nameFr: 'Bir El Ater' },
  { wilayaCode: '12', nameAr: 'نقرين', nameFr: 'Negrine' },
  { wilayaCode: '12', nameAr: 'الحمماث', nameFr: 'El Houidjbet' },
  { wilayaCode: '12', nameAr: 'تليلان', nameFr: 'Thlija' },
  { wilayaCode: '12', nameAr: 'مرسط', nameFr: 'Morsott' },
  { wilayaCode: '12', nameAr: 'ونزة', nameFr: 'Ouenza' },
  { wilayaCode: '12', nameAr: 'الكويف', nameFr: 'El Kouif' },
  { wilayaCode: '12', nameAr: 'الماء الأبيض', nameFr: 'El Ma El Abiodh' },
  { wilayaCode: '12', nameAr: 'الجرف', nameFr: 'El Djorf' },
  { wilayaCode: '12', nameAr: 'العقلة', nameFr: 'Oglet Merteba' },
  { wilayaCode: '12', nameAr: 'ثليجان', nameFr: 'Tlidjene' },
  // ── 13 Tlemcen ────────────────────────────────────────────────────
  { wilayaCode: '13', nameAr: 'تلمسان', nameFr: 'Tlemcen' },
  { wilayaCode: '13', nameAr: 'مغنية', nameFr: 'Maghnia' },
  { wilayaCode: '13', nameAr: 'ندرومة', nameFr: 'Nedroma' },
  { wilayaCode: '13', nameAr: 'غزوات', nameFr: 'Ghazaouet' },
  { wilayaCode: '13', nameAr: 'بني مستر', nameFr: 'Beni Mester' },
  { wilayaCode: '13', nameAr: 'سيدي العبد', nameFr: 'Sidi Abdelli' },
  { wilayaCode: '13', nameAr: 'رمشي', nameFr: 'Remchi' },
  { wilayaCode: '13', nameAr: 'فلاوسن', nameFr: 'Fellaoucene' },
  { wilayaCode: '13', nameAr: 'هنين', nameFr: 'Hennaya' },
  { wilayaCode: '13', nameAr: 'بابا حسن', nameFr: 'Bab El Assa' },
  { wilayaCode: '13', nameAr: 'سبعة', nameFr: 'Sebaa Chioukh' },
  { wilayaCode: '13', nameAr: 'منصورة', nameFr: 'Mansourah' },
  { wilayaCode: '13', nameAr: 'أولاد ميمون', nameFr: 'Ouled Mimoun' },
  { wilayaCode: '13', nameAr: 'سيدي سنوسي', nameFr: 'Sidi Senoussi' },
  { wilayaCode: '13', nameAr: 'بني سنوس', nameFr: 'Beni Snous' },
  { wilayaCode: '13', nameAr: 'بني بوسعيد', nameFr: 'Beni Boussaid' },
  { wilayaCode: '13', nameAr: 'سوق الثلاثاء', nameFr: 'Souk El Had' },
  // ── 14 Tiaret ─────────────────────────────────────────────────────
  { wilayaCode: '14', nameAr: 'تيارت', nameFr: 'Tiaret' },
  { wilayaCode: '14', nameAr: 'فرندة', nameFr: 'Frenda' },
  { wilayaCode: '14', nameAr: 'عين دهب', nameFr: 'Aïn Deheb' },
  { wilayaCode: '14', nameAr: 'مهدية', nameFr: 'Mahdia' },
  { wilayaCode: '14', nameAr: 'دحمانية', nameFr: 'Dahmouni' },
  { wilayaCode: '14', nameAr: 'القصب', nameFr: 'Guertoufa' },
  { wilayaCode: '14', nameAr: 'ستيتن', nameFr: 'Sidi Ali Mellal' },
  { wilayaCode: '14', nameAr: 'واد ليلي', nameFr: 'Oued Lilli' },
  { wilayaCode: '14', nameAr: 'خرزوز', nameFr: 'Ksar Chellala' },
  { wilayaCode: '14', nameAr: 'مضويد', nameFr: 'Medrissa' },
  { wilayaCode: '14', nameAr: 'رحابية', nameFr: 'Rahouia' },
  { wilayaCode: '14', nameAr: 'الوادي', nameFr: 'Sidi Bakhti' },
  { wilayaCode: '14', nameAr: 'أولاد جيلالي', nameFr: 'Ouled Djillali' },
  { wilayaCode: '14', nameAr: 'سيدي الدجيلي', nameFr: 'Mechraa Safa' },
  { wilayaCode: '14', nameAr: 'قصر الشلالة', nameFr: 'Ksar El Chellala' },
  // ── 15 Tizi Ouzou ─────────────────────────────────────────────────
  { wilayaCode: '15', nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou' },
  { wilayaCode: '15', nameAr: 'عين الحمام', nameFr: 'Aïn El Hammam' },
  { wilayaCode: '15', nameAr: 'بني دوالة', nameFr: 'Beni Douala' },
  { wilayaCode: '15', nameAr: 'بوزقن', nameFr: 'Bouzeguene' },
  { wilayaCode: '15', nameAr: 'ذراع الميزان', nameFr: 'Draâ El Mizan' },
  { wilayaCode: '15', nameAr: 'ازفون', nameFr: 'Azeffoun' },
  { wilayaCode: '15', nameAr: 'تيزي غنيف', nameFr: 'Tizi Gheniff' },
  { wilayaCode: '15', nameAr: 'أعزازقا', nameFr: 'Azazga' },
  { wilayaCode: '15', nameAr: 'تيزي رشد', nameFr: 'Tigzirt' },
  { wilayaCode: '15', nameAr: 'لربعاء ناث إيراثن', nameFr: 'Larbaâ Nath Irathen' },
  { wilayaCode: '15', nameAr: 'ماطماطة', nameFr: 'Maâtkas' },
  { wilayaCode: '15', nameAr: 'تيقزيرت', nameFr: 'Tigzirt' },
  { wilayaCode: '15', nameAr: 'مخلوف', nameFr: 'Iferhounene' },
  { wilayaCode: '15', nameAr: 'واضية', nameFr: 'Ouadhia' },
  { wilayaCode: '15', nameAr: 'أيت يحيى', nameFr: 'Aïth Yahia' },
  { wilayaCode: '15', nameAr: 'بوجيمة', nameFr: 'Freha' },
  { wilayaCode: '15', nameAr: 'يطافن', nameFr: 'Iflissen' },
  { wilayaCode: '15', nameAr: 'أيت عيسى ميمون', nameFr: 'Aïts Zmenzer' },
  // ── 16 Alger ──────────────────────────────────────────────────────
  { wilayaCode: '16', nameAr: 'الجزائر الوسطى', nameFr: 'Alger Centre' },
  { wilayaCode: '16', nameAr: 'باب الوادي', nameFr: 'Bab El Oued' },
  { wilayaCode: '16', nameAr: 'الحراش', nameFr: 'El Harrach' },
  { wilayaCode: '16', nameAr: 'بابا حسن', nameFr: 'Baba Hassen' },
  { wilayaCode: '16', nameAr: 'بئر مراد رايس', nameFr: 'Bir Mourad Raïs' },
  { wilayaCode: '16', nameAr: 'بن عكنون', nameFr: 'Ben Aknoun' },
  { wilayaCode: '16', nameAr: 'الدار البيضاء', nameFr: 'Dar El Beïda' },
  { wilayaCode: '16', nameAr: 'دالي إبراهيم', nameFr: 'Dély Ibrahim' },
  { wilayaCode: '16', nameAr: 'درارية', nameFr: 'Draria' },
  { wilayaCode: '16', nameAr: 'القبة', nameFr: 'El Biar' },
  { wilayaCode: '16', nameAr: 'المرادية', nameFr: 'Hydra' },
  { wilayaCode: '16', nameAr: 'حسين داي', nameFr: 'Hussein Dey' },
  { wilayaCode: '16', nameAr: 'الرغاية', nameFr: 'Rouïba' },
  { wilayaCode: '16', nameAr: 'الشراقة', nameFr: 'Chéraga' },
  { wilayaCode: '16', nameAr: 'سيدي امحمد', nameFr: 'Sidi M\'Hamed' },
  { wilayaCode: '16', nameAr: 'المحمدية', nameFr: 'Mohammadia' },
  { wilayaCode: '16', nameAr: 'بوزريعة', nameFr: 'Bouzareah' },
  { wilayaCode: '16', nameAr: 'المقرية', nameFr: 'El Magharia' },
  { wilayaCode: '16', nameAr: 'خرايسية', nameFr: 'Khraïcia' },
  { wilayaCode: '16', nameAr: 'عين البنيان', nameFr: 'Ain Benian' },
  { wilayaCode: '16', nameAr: 'بئر توتة', nameFr: 'Bir Touta' },
  { wilayaCode: '16', nameAr: 'الكاليتوس', nameFr: 'Les Eucalyptus' },
  { wilayaCode: '16', nameAr: 'عين طاية', nameFr: 'Aïn Taya' },
  { wilayaCode: '16', nameAr: 'القليعة', nameFr: 'Kouba' },
  { wilayaCode: '16', nameAr: 'بئر الجير', nameFr: 'Birtouta' },
  { wilayaCode: '16', nameAr: 'سطاوالي', nameFr: 'Staoueli' },
  { wilayaCode: '16', nameAr: 'زرالدة', nameFr: 'Zeralda' },
  { wilayaCode: '16', nameAr: 'الرويبة', nameFr: 'Rouïba' },
  { wilayaCode: '16', nameAr: 'شراغة', nameFr: 'Saoula' },
  { wilayaCode: '16', nameAr: 'سيدي موسى', nameFr: 'Sidi Moussa' },
  { wilayaCode: '16', nameAr: 'الدرارية', nameFr: 'Douera' },
  { wilayaCode: '16', nameAr: 'دويرة', nameFr: 'Douera' },
  { wilayaCode: '16', nameAr: 'القرمة', nameFr: 'Baraki' },
  { wilayaCode: '16', nameAr: 'براقي', nameFr: 'Baraki' },
  // ── 17 Djelfa ─────────────────────────────────────────────────────
  { wilayaCode: '17', nameAr: 'الجلفة', nameFr: 'Djelfa' },
  { wilayaCode: '17', nameAr: 'عين معبد', nameFr: 'Aïn Maâbed' },
  { wilayaCode: '17', nameAr: 'بنهار', nameFr: 'Benhar' },
  { wilayaCode: '17', nameAr: 'مسعد', nameFr: 'Messaad' },
  { wilayaCode: '17', nameAr: 'سيدي لعجال', nameFr: 'Sidi Ladjal' },
  { wilayaCode: '17', nameAr: 'دار الشيوخ', nameFr: 'Dar Chioukh' },
  { wilayaCode: '17', nameAr: 'عين وسارة', nameFr: 'Aïn Oussara' },
  { wilayaCode: '17', nameAr: 'الإدريسية', nameFr: 'Idrissia' },
  { wilayaCode: '17', nameAr: 'زكار', nameFr: 'Zakar' },
  { wilayaCode: '17', nameAr: 'حاسي بحبح', nameFr: 'Hassi Bahbah' },
  { wilayaCode: '17', nameAr: 'عين الإبل', nameFr: 'Aïn El Ibel' },
  { wilayaCode: '17', nameAr: 'سلمانة', nameFr: 'Selmana' },
  { wilayaCode: '17', nameAr: 'المجبارة', nameFr: 'El Guedid' },
  { wilayaCode: '17', nameAr: 'القطارة', nameFr: 'El Khemis' },
  // ── 18 Jijel ──────────────────────────────────────────────────────
  { wilayaCode: '18', nameAr: 'جيجل', nameFr: 'Jijel' },
  { wilayaCode: '18', nameAr: 'الطاهير', nameFr: 'El Milia' },
  { wilayaCode: '18', nameAr: 'الميلية', nameFr: 'El Milia' },
  { wilayaCode: '18', nameAr: 'أمجاز أيدير', nameFr: 'Amjadz Idir' },
  { wilayaCode: '18', nameAr: 'بوراوي بلهادف', nameFr: 'Borari Belhadef' },
  { wilayaCode: '18', nameAr: 'غبالة', nameFr: 'Ghebala' },
  { wilayaCode: '18', nameAr: 'الشقفة', nameFr: 'Chekfa' },
  { wilayaCode: '18', nameAr: 'القنار نيشيدة', nameFr: 'El Kennar' },
  { wilayaCode: '18', nameAr: 'الوطاية', nameFr: 'Texenna' },
  { wilayaCode: '18', nameAr: 'تكسنة', nameFr: 'Taher' },
  { wilayaCode: '18', nameAr: 'سيدي ماحوس', nameFr: 'Sidi Maarouf' },
  { wilayaCode: '18', nameAr: 'الأمير عبد القادر', nameFr: 'Emir Abdelkader' },
  { wilayaCode: '18', nameAr: 'الجمعة بني حبيبي', nameFr: 'Djemaa Beni Habibi' },
  // ── 19 Sétif ──────────────────────────────────────────────────────
  { wilayaCode: '19', nameAr: 'سطيف', nameFr: 'Sétif' },
  { wilayaCode: '19', nameAr: 'الأرنا', nameFr: 'El Eulma' },
  { wilayaCode: '19', nameAr: 'عين ولمان', nameFr: 'Aïn Oulmane' },
  { wilayaCode: '19', nameAr: 'قجال', nameFr: 'Guidjel' },
  { wilayaCode: '19', nameAr: 'بئر العرش', nameFr: 'Bir El Arch' },
  { wilayaCode: '19', nameAr: 'عين أزال', nameFr: 'Aïn Azel' },
  { wilayaCode: '19', nameAr: 'البيضاء', nameFr: 'El Beida' },
  { wilayaCode: '19', nameAr: 'الوناسة', nameFr: 'El Ounas' },
  { wilayaCode: '19', nameAr: 'بازر صخرة', nameFr: 'Bazer Sakhra' },
  { wilayaCode: '19', nameAr: 'عين آرنات', nameFr: 'Aïn Arnat' },
  { wilayaCode: '19', nameAr: 'صالح باي', nameFr: 'Salah Bey' },
  { wilayaCode: '19', nameAr: 'راس الماء', nameFr: 'Ras El Ma' },
  { wilayaCode: '19', nameAr: 'عموشة', nameFr: 'Amoucha' },
  { wilayaCode: '19', nameAr: 'بوقاعة', nameFr: 'Bougaa' },
  { wilayaCode: '19', nameAr: 'المعاضيد', nameFr: 'Maâdid' },
  { wilayaCode: '19', nameAr: 'الكلتة', nameFr: 'Bellaa' },
  { wilayaCode: '19', nameAr: 'عين الروى', nameFr: 'Aïn Roua' },
  // ── 20 Saïda ──────────────────────────────────────────────────────
  { wilayaCode: '20', nameAr: 'سعيدة', nameFr: 'Saïda' },
  { wilayaCode: '20', nameAr: 'عين الحجر', nameFr: 'Aïn El Hadjar' },
  { wilayaCode: '20', nameAr: 'يوب', nameFr: 'Youb' },
  { wilayaCode: '20', nameAr: 'حساسنة', nameFr: 'Hassasna' },
  { wilayaCode: '20', nameAr: 'دوي الثابتي', nameFr: 'Doui Thabet' },
  { wilayaCode: '20', nameAr: 'عين سلطان', nameFr: 'Aïn Soltane' },
  { wilayaCode: '20', nameAr: 'رحابية', nameFr: 'Rebahia' },
  { wilayaCode: '20', nameAr: 'مولاي لرباح', nameFr: 'Moulay Larbi' },
  { wilayaCode: '20', nameAr: 'الماء البياض', nameFr: 'El Maamoraa' },
  { wilayaCode: '20', nameAr: 'أولاد إبراهيم', nameFr: 'Ouled Brahim' },
  // ── 21 Skikda ─────────────────────────────────────────────────────
  { wilayaCode: '21', nameAr: 'سكيكدة', nameFr: 'Skikda' },
  { wilayaCode: '21', nameAr: 'عزابة', nameFr: 'Azzaba' },
  { wilayaCode: '21', nameAr: 'الحروش', nameFr: 'El Harrouch' },
  { wilayaCode: '21', nameAr: 'القل', nameFr: 'El Qoll' },
  { wilayaCode: '21', nameAr: 'رمضان جمال', nameFr: 'Ramdane Djamel' },
  { wilayaCode: '21', nameAr: 'كوريشي', nameFr: 'Collo' },
  { wilayaCode: '21', nameAr: 'سالاح بزيو', nameFr: 'Salah Bouchaour' },
  { wilayaCode: '21', nameAr: 'آيت تغريت', nameFr: 'Aïn Cherchar' },
  { wilayaCode: '21', nameAr: 'واد الزهور', nameFr: 'Oued Zehour' },
  { wilayaCode: '21', nameAr: 'واد الكبير', nameFr: 'Oued El Kebir' },
  { wilayaCode: '21', nameAr: 'توزة', nameFr: 'Tamalous' },
  { wilayaCode: '21', nameAr: 'زردازة', nameFr: 'Zerdazene' },
  { wilayaCode: '21', nameAr: 'بن عزوز', nameFr: 'Bein El Ouidane' },
  // ── 22 Sidi Bel Abbès ─────────────────────────────────────────────
  { wilayaCode: '22', nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel Abbès' },
  { wilayaCode: '22', nameAr: 'سفيزف', nameFr: 'Sfizef' },
  { wilayaCode: '22', nameAr: 'مرحوم', nameFr: 'Marhoum' },
  { wilayaCode: '22', nameAr: 'ولهاصة', nameFr: 'Oulhassa El Gheraba' },
  { wilayaCode: '22', nameAr: 'بئر الحمام', nameFr: 'Bir El Hammam' },
  { wilayaCode: '22', nameAr: 'لحمر', nameFr: 'Lahmmar' },
  { wilayaCode: '22', nameAr: 'مشرفة', nameFr: 'Mcheraa Houari' },
  { wilayaCode: '22', nameAr: 'تنيرة', nameFr: 'Tenira' },
  { wilayaCode: '22', nameAr: 'بوخنيفيس', nameFr: 'Sidi Lahcene' },
  { wilayaCode: '22', nameAr: 'سيدي إبراهيم', nameFr: 'Sidi Khaled' },
  { wilayaCode: '22', nameAr: 'مزة', nameFr: 'Zerouala' },
  { wilayaCode: '22', nameAr: 'الحصبة', nameFr: 'Tessala' },
  { wilayaCode: '22', nameAr: 'رأس الماء', nameFr: 'Ras El Maa' },
  { wilayaCode: '22', nameAr: 'سيدي يوسف', nameFr: 'Sidi Youcef' },
  { wilayaCode: '22', nameAr: 'حاسي زهانة', nameFr: 'Hassi Zahana' },
  { wilayaCode: '22', nameAr: 'عين تريدمانة', nameFr: 'Aïn Tindamine' },
  // ── 23 Annaba ─────────────────────────────────────────────────────
  { wilayaCode: '23', nameAr: 'عنابة', nameFr: 'Annaba' },
  { wilayaCode: '23', nameAr: 'الحجار', nameFr: 'El Hadjar' },
  { wilayaCode: '23', nameAr: 'الشرفة', nameFr: 'Chetaibi' },
  { wilayaCode: '23', nameAr: 'سرايدي', nameFr: 'Seraïdi' },
  { wilayaCode: '23', nameAr: 'برحال', nameFr: 'Berrahal' },
  { wilayaCode: '23', nameAr: 'الصدادنة', nameFr: 'Es Seddikia' },
  { wilayaCode: '23', nameAr: 'الشطية', nameFr: 'Oued El Aneb' },
  { wilayaCode: '23', nameAr: 'عين الباردة', nameFr: 'Aïn El Berda' },
  // ── 24 Guelma ─────────────────────────────────────────────────────
  { wilayaCode: '24', nameAr: 'قالمة', nameFr: 'Guelma' },
  { wilayaCode: '24', nameAr: 'بوشقوف', nameFr: 'Bouchegouf' },
  { wilayaCode: '24', nameAr: 'خزارة', nameFr: 'Khezara' },
  { wilayaCode: '24', nameAr: 'النشيمة', nameFr: 'Nechmaya' },
  { wilayaCode: '24', nameAr: 'بلخير', nameFr: 'Belkheir' },
  { wilayaCode: '24', nameAr: 'الفجوج', nameFr: 'Oued Zenati' },
  { wilayaCode: '24', nameAr: 'عين بن بيضاء', nameFr: 'Aïn Bou Beida' },
  { wilayaCode: '24', nameAr: 'مجاز عمار', nameFr: 'Medjaz Sfa' },
  { wilayaCode: '24', nameAr: 'عين مخلوف', nameFr: 'Aïn Makhlouf' },
  { wilayaCode: '24', nameAr: 'هيليوبوليس', nameFr: 'Heliopolis' },
  { wilayaCode: '24', nameAr: 'قلعة بوصبع', nameFr: 'Roknia' },
  // ── 25 Constantine ────────────────────────────────────────────────
  { wilayaCode: '25', nameAr: 'قسنطينة', nameFr: 'Constantine' },
  { wilayaCode: '25', nameAr: 'الخروب', nameFr: 'El Khroub' },
  { wilayaCode: '25', nameAr: 'حامة بوزيان', nameFr: 'Hamma Bouziane' },
  { wilayaCode: '25', nameAr: 'ديدوش مراد', nameFr: 'Didouche Mourad' },
  { wilayaCode: '25', nameAr: 'عين عبيد', nameFr: 'Aïn Abid' },
  { wilayaCode: '25', nameAr: 'زيغود يوسف', nameFr: 'Zighoud Youcef' },
  { wilayaCode: '25', nameAr: 'ابن باديس', nameFr: 'Ibn Badis' },
  { wilayaCode: '25', nameAr: 'أبوعبدالله', nameFr: 'Beni Hamidan' },
  { wilayaCode: '25', nameAr: 'مسعود بوجريو', nameFr: 'Mesaud' },
  { wilayaCode: '25', nameAr: 'عين سمارة', nameFr: 'Aïn Smara' },
  { wilayaCode: '25', nameAr: 'بني حميدان', nameFr: 'Beni Hamidan' },
  // ── 26 Médéa ──────────────────────────────────────────────────────
  { wilayaCode: '26', nameAr: 'المدية', nameFr: 'Médéa' },
  { wilayaCode: '26', nameAr: 'الكاف الأخضر', nameFr: 'El Kef El Akhdar' },
  { wilayaCode: '26', nameAr: 'عزيز', nameFr: 'Aziz' },
  { wilayaCode: '26', nameAr: 'بجموعة', nameFr: 'Beni Slimane' },
  { wilayaCode: '26', nameAr: 'بوعيش', nameFr: 'Bouaiche' },
  { wilayaCode: '26', nameAr: 'كافيات', nameFr: 'Kefayet' },
  { wilayaCode: '26', nameAr: 'عين بوسيف', nameFr: 'Aïn Boucif' },
  { wilayaCode: '26', nameAr: 'عين دهب', nameFr: 'Aïn Ouksoul' },
  { wilayaCode: '26', nameAr: 'دراقل', nameFr: 'Draa El Mizan' },
  { wilayaCode: '26', nameAr: 'سوق الأحد', nameFr: 'Souk El Had' },
  { wilayaCode: '26', nameAr: 'بني سليمان', nameFr: 'Beni Slimane' },
  { wilayaCode: '26', nameAr: 'سيدي نعمان', nameFr: 'Sidi Naâmane' },
  { wilayaCode: '26', nameAr: 'قصر بوخاري', nameFr: 'Ksar El Boukhari' },
  { wilayaCode: '26', nameAr: 'الدجنان', nameFr: 'Djouab' },
  { wilayaCode: '26', nameAr: 'مجبر', nameFr: 'Meghraoua' },
  // ── 27 Mostaganem ─────────────────────────────────────────────────
  { wilayaCode: '27', nameAr: 'مستغانم', nameFr: 'Mostaganem' },
  { wilayaCode: '27', nameAr: 'مسرغين', nameFr: 'Mesra' },
  { wilayaCode: '27', nameAr: 'حاسي ماماش', nameFr: 'Hassi Mameche' },
  { wilayaCode: '27', nameAr: 'منصورة', nameFr: 'Mansourah' },
  { wilayaCode: '27', nameAr: 'ماسرا', nameFr: 'Khadra' },
  { wilayaCode: '27', nameAr: 'العيون', nameFr: 'Aïn Tedles' },
  { wilayaCode: '27', nameAr: 'عين تادلس', nameFr: 'Aïn Tedles' },
  { wilayaCode: '27', nameAr: 'صافية', nameFr: 'Safia' },
  { wilayaCode: '27', nameAr: 'الصفصاف', nameFr: 'Abdelmalek Ramdan' },
  { wilayaCode: '27', nameAr: 'موزاية', nameFr: 'Bouguirat' },
  { wilayaCode: '27', nameAr: 'سيدي علي', nameFr: 'Sidi Ali' },
  { wilayaCode: '27', nameAr: 'عشعاشة', nameFr: 'Achacha' },
  // ── 28 M'Sila ─────────────────────────────────────────────────────
  { wilayaCode: '28', nameAr: 'المسيلة', nameFr: 'M\'Sila' },
  { wilayaCode: '28', nameAr: 'بوسعادة', nameFr: 'Bou Saâda' },
  { wilayaCode: '28', nameAr: 'عين الريش', nameFr: 'Aïn El Rich' },
  { wilayaCode: '28', nameAr: 'سيدي عيسى', nameFr: 'Sidi Aissa' },
  { wilayaCode: '28', nameAr: 'المعاضيد', nameFr: 'El Maadhid' },
  { wilayaCode: '28', nameAr: 'ماضنة', nameFr: 'Magra' },
  { wilayaCode: '28', nameAr: 'السليم', nameFr: 'Chellal' },
  { wilayaCode: '28', nameAr: 'المطارفة', nameFr: 'El Mecili' },
  { wilayaCode: '28', nameAr: 'بن سرور', nameFr: 'Ouanougha' },
  { wilayaCode: '28', nameAr: 'شلال', nameFr: 'Belaiba' },
  { wilayaCode: '28', nameAr: 'سيدي امحمد', nameFr: 'Sidi M\'Hamed' },
  { wilayaCode: '28', nameAr: 'حمام الضلعة', nameFr: 'Hammam Delaa' },
  // ── 29 Mascara ────────────────────────────────────────────────────
  { wilayaCode: '29', nameAr: 'معسكر', nameFr: 'Mascara' },
  { wilayaCode: '29', nameAr: 'سيق', nameFr: 'Sig' },
  { wilayaCode: '29', nameAr: 'خلويق', nameFr: 'Ghriss' },
  { wilayaCode: '29', nameAr: 'المحمدية', nameFr: 'Mohammadia' },
  { wilayaCode: '29', nameAr: 'بن عشي', nameFr: 'Bou Henni' },
  { wilayaCode: '29', nameAr: 'قرجوم', nameFr: 'Guergueville' },
  { wilayaCode: '29', nameAr: 'حاسي ممدوح', nameFr: 'Hassi Mameche' },
  { wilayaCode: '29', nameAr: 'تيزي', nameFr: 'Tizi' },
  { wilayaCode: '29', nameAr: 'بوهني', nameFr: 'Bouhannia' },
  { wilayaCode: '29', nameAr: 'عين فارس', nameFr: 'Aïn Fares' },
  { wilayaCode: '29', nameAr: 'ماوسة', nameFr: 'Maoussa' },
  { wilayaCode: '29', nameAr: 'قرايلية', nameFr: 'Oued El Abtal' },
  // ── 30 Ouargla ────────────────────────────────────────────────────
  { wilayaCode: '30', nameAr: 'ورقلة', nameFr: 'Ouargla' },
  { wilayaCode: '30', nameAr: 'حاسي مسعود', nameFr: 'Hassi Messaoud' },
  { wilayaCode: '30', nameAr: 'سيدي خويلد', nameFr: 'Sidi Khouiled' },
  { wilayaCode: '30', nameAr: 'المقارين', nameFr: 'El Mekhadma' },
  { wilayaCode: '30', nameAr: 'النقوسة', nameFr: 'N\'Goussa' },
  { wilayaCode: '30', nameAr: 'تبركانت', nameFr: 'Tebesbest' },
  { wilayaCode: '30', nameAr: 'تيبيسبست', nameFr: 'Tibesbest' },
  { wilayaCode: '30', nameAr: 'أنقوسة', nameFr: 'Ain Beida' },
  { wilayaCode: '30', nameAr: 'روقة', nameFr: 'Rouisat' },
  { wilayaCode: '30', nameAr: 'تقرت', nameFr: 'Touggourt' },
  // ── 31 Oran ───────────────────────────────────────────────────────
  { wilayaCode: '31', nameAr: 'وهران', nameFr: 'Oran' },
  { wilayaCode: '31', nameAr: 'عين الترك', nameFr: 'Aïn El Turk' },
  { wilayaCode: '31', nameAr: 'بئر الجير', nameFr: 'Bir El Djir' },
  { wilayaCode: '31', nameAr: 'عرزيو', nameFr: 'Arzew' },
  { wilayaCode: '31', nameAr: 'مرسى الكبير', nameFr: 'Mers El Kébir' },
  { wilayaCode: '31', nameAr: 'السانية', nameFr: 'Es Sénia' },
  { wilayaCode: '31', nameAr: 'حاسي بن عقبة', nameFr: 'Hassi Ben Okba' },
  { wilayaCode: '31', nameAr: 'وادي تليلات', nameFr: 'Oued Tlelat' },
  { wilayaCode: '31', nameAr: 'طافراوي', nameFr: 'Tafraoui' },
  { wilayaCode: '31', nameAr: 'بطيوة', nameFr: 'Btiouet' },
  { wilayaCode: '31', nameAr: 'الكرمة', nameFr: 'El Kerma' },
  { wilayaCode: '31', nameAr: 'بن فريحة', nameFr: 'Ben Freha' },
  { wilayaCode: '31', nameAr: 'عين الكرمة', nameFr: 'Aïn Kerma' },
  { wilayaCode: '31', nameAr: 'بوتلليس', nameFr: 'Boutlelis' },
  { wilayaCode: '31', nameAr: 'سيدي الشحمي', nameFr: 'Sidi Chami' },
  { wilayaCode: '31', nameAr: 'المرسى الكبير', nameFr: 'Gdyel' },
  // ── 32 El Bayadh ──────────────────────────────────────────────────
  { wilayaCode: '32', nameAr: 'البيض', nameFr: 'El Bayadh' },
  { wilayaCode: '32', nameAr: 'بريزينة', nameFr: 'Brezina' },
  { wilayaCode: '32', nameAr: 'الأبيض سيدي الشيخ', nameFr: 'El Abiodh Sidi Cheikh' },
  { wilayaCode: '32', nameAr: 'بن يعقوب', nameFr: 'Ben Yacoub' },
  { wilayaCode: '32', nameAr: 'بوقطب', nameFr: 'Bougtob' },
  { wilayaCode: '32', nameAr: 'المحرة', nameFr: 'El Mehara' },
  { wilayaCode: '32', nameAr: 'ستي بلال', nameFr: 'Sidi Tifour' },
  { wilayaCode: '32', nameAr: 'الخيثر', nameFr: 'El Khitha' },
  { wilayaCode: '32', nameAr: 'العسلة', nameFr: 'Boualem' },
  { wilayaCode: '32', nameAr: 'كراكدة', nameFr: 'Kraakda' },
  { wilayaCode: '32', nameAr: 'بوعلام', nameFr: 'Boualem' },
  // ── 33 Illizi ─────────────────────────────────────────────────────
  { wilayaCode: '33', nameAr: 'إليزي', nameFr: 'Illizi' },
  { wilayaCode: '33', nameAr: 'عين أميناس', nameFr: 'Aïn Amenas' },
  { wilayaCode: '33', nameAr: 'دبدب', nameFr: 'Debdeb' },
  { wilayaCode: '33', nameAr: 'برج عمر إدريس', nameFr: 'Bordj Omar Driss' },
  // ── 34 Bordj Bou Arréridj ─────────────────────────────────────────
  { wilayaCode: '34', nameAr: 'برج بوعريريج', nameFr: 'Bordj Bou Arréridj' },
  { wilayaCode: '34', nameAr: 'رأس الوادي', nameFr: 'Ras El Oued' },
  { wilayaCode: '34', nameAr: 'برج غدير', nameFr: 'Bordj Ghedir' },
  { wilayaCode: '34', nameAr: 'المنصورة', nameFr: 'Mansourah' },
  { wilayaCode: '34', nameAr: 'قيقبة', nameFr: 'Ouled Dahmane' },
  { wilayaCode: '34', nameAr: 'المجانة', nameFr: 'El Mhir' },
  { wilayaCode: '34', nameAr: 'الحمادية', nameFr: 'Hasnaoua' },
  { wilayaCode: '34', nameAr: 'مناعة', nameFr: 'Manaa' },
  { wilayaCode: '34', nameAr: 'العش', nameFr: 'El Ach' },
  { wilayaCode: '34', nameAr: 'كلاح', nameFr: 'Khelil' },
  { wilayaCode: '34', nameAr: 'أولاد داود', nameFr: 'Ouled Daoud' },
  { wilayaCode: '34', nameAr: 'سيدي امبارك', nameFr: 'Sidi Embarek' },
  { wilayaCode: '34', nameAr: 'تيكسابت', nameFr: 'Tikasbite' },
  // ── 35 Boumerdès ──────────────────────────────────────────────────
  { wilayaCode: '35', nameAr: 'بومرداس', nameFr: 'Boumerdès' },
  { wilayaCode: '35', nameAr: 'دلس', nameFr: 'Dellys' },
  { wilayaCode: '35', nameAr: 'بودواو', nameFr: 'Boudouaou' },
  { wilayaCode: '35', nameAr: 'ثنية المايل', nameFr: 'Theniet El Abed' },
  { wilayaCode: '35', nameAr: 'الخروبة', nameFr: 'Khemis El Khechna' },
  { wilayaCode: '35', nameAr: 'بوزقن', nameFr: 'Bouzeguen' },
  { wilayaCode: '35', nameAr: 'قورصو', nameFr: 'Corso' },
  { wilayaCode: '35', nameAr: 'عين طاية', nameFr: 'Aïn Taya' },
  { wilayaCode: '35', nameAr: 'أفير', nameFr: 'Afir' },
  { wilayaCode: '35', nameAr: 'تيجلابين', nameFr: 'Tidjelabine' },
  { wilayaCode: '35', nameAr: 'سيدي داود', nameFr: 'Sidi Daoud' },
  { wilayaCode: '35', nameAr: 'برج منايل', nameFr: 'Bordj Menaiel' },
  { wilayaCode: '35', nameAr: 'زموري', nameFr: 'Zemmouri' },
  { wilayaCode: '35', nameAr: 'لقاطة', nameFr: 'Laghata' },
  // ── 36 El Tarf ────────────────────────────────────────────────────
  { wilayaCode: '36', nameAr: 'الطارف', nameFr: 'El Tarf' },
  { wilayaCode: '36', nameAr: 'الشط', nameFr: 'El Chatt' },
  { wilayaCode: '36', nameAr: 'حمام بني صالح', nameFr: 'Hammam Beni Salah' },
  { wilayaCode: '36', nameAr: 'بوقوس', nameFr: 'Bouhadjar' },
  { wilayaCode: '36', nameAr: 'الشافية', nameFr: 'Chefia' },
  { wilayaCode: '36', nameAr: 'زيتونة', nameFr: 'Zitouna' },
  { wilayaCode: '36', nameAr: 'بن مهيدي', nameFr: 'Ben Mehidi' },
  { wilayaCode: '36', nameAr: 'الكالة', nameFr: 'El Kala' },
  { wilayaCode: '36', nameAr: 'عين العسل', nameFr: 'Aïn El Assel' },
  { wilayaCode: '36', nameAr: 'عوينات', nameFr: 'Aouinet' },
  { wilayaCode: '36', nameAr: 'سوق أهراس', nameFr: 'Zerizer' },
  // ── 37 Tindouf ────────────────────────────────────────────────────
  { wilayaCode: '37', nameAr: 'تندوف', nameFr: 'Tindouf' },
  { wilayaCode: '37', nameAr: 'أوكسان', nameFr: 'Ouksane' },
  // ── 38 Tissemsilt ─────────────────────────────────────────────────
  { wilayaCode: '38', nameAr: 'تيسمسيلت', nameFr: 'Tissemsilt' },
  { wilayaCode: '38', nameAr: 'لرجام', nameFr: 'Lazharia' },
  { wilayaCode: '38', nameAr: 'لمصب', nameFr: 'El Meslem' },
  { wilayaCode: '38', nameAr: 'ثنية الأحد', nameFr: 'Theniet El Had' },
  { wilayaCode: '38', nameAr: 'بني شعيب', nameFr: 'Beni Chaib' },
  { wilayaCode: '38', nameAr: 'سيدي العنتري', nameFr: 'Sidi Lantri' },
  { wilayaCode: '38', nameAr: 'كزلة', nameFr: 'Khemisti' },
  { wilayaCode: '38', nameAr: 'الحشيمة', nameFr: 'Ouled Besssem' },
  { wilayaCode: '38', nameAr: 'عين الذهب', nameFr: 'Aïn Dzahb' },
  { wilayaCode: '38', nameAr: 'العمارية', nameFr: 'Ammari' },
  // ── 39 El Oued ────────────────────────────────────────────────────
  { wilayaCode: '39', nameAr: 'الوادي', nameFr: 'El Oued' },
  { wilayaCode: '39', nameAr: 'الرباح', nameFr: 'Robbah' },
  { wilayaCode: '39', nameAr: 'دبيلة', nameFr: 'Debila' },
  { wilayaCode: '39', nameAr: 'تاغزوت', nameFr: 'Taghzout' },
  { wilayaCode: '39', nameAr: 'الطالب العربي', nameFr: 'Taleb Larbi' },
  { wilayaCode: '39', nameAr: 'الشطة', nameFr: 'Sidi Aoun' },
  { wilayaCode: '39', nameAr: 'قمار', nameFr: 'Guemmar' },
  { wilayaCode: '39', nameAr: 'البياضة', nameFr: 'Bayada' },
  { wilayaCode: '39', nameAr: 'سيدي عون', nameFr: 'Sidi Aoun' },
  { wilayaCode: '39', nameAr: 'رقيبة', nameFr: 'Reguiba' },
  { wilayaCode: '39', nameAr: 'حاسي خليفة', nameFr: 'Hassi Khalifa' },
  { wilayaCode: '39', nameAr: 'أولاد ربيع', nameFr: 'Ouled Rabah' },
  { wilayaCode: '39', nameAr: 'الحمرة', nameFr: 'Hamraia' },
  { wilayaCode: '39', nameAr: 'كوينين', nameFr: 'Kouinine' },
  { wilayaCode: '39', nameAr: 'ورماس', nameFr: 'Ourmas' },
  // ── 40 Khenchela ──────────────────────────────────────────────────
  { wilayaCode: '40', nameAr: 'خنشلة', nameFr: 'Khenchela' },
  { wilayaCode: '40', nameAr: 'طامزة', nameFr: 'Tamza' },
  { wilayaCode: '40', nameAr: 'ماستة', nameFr: 'Msara' },
  { wilayaCode: '40', nameAr: 'بابار', nameFr: 'Babar' },
  { wilayaCode: '40', nameAr: 'شلية', nameFr: 'Chellia' },
  { wilayaCode: '40', nameAr: 'قايس', nameFr: 'Kaïs' },
  { wilayaCode: '40', nameAr: 'الرميلة', nameFr: 'Remila' },
  { wilayaCode: '40', nameAr: 'يابوس', nameFr: 'Yabous' },
  { wilayaCode: '40', nameAr: 'بغاي', nameFr: 'Baghai' },
  { wilayaCode: '40', nameAr: 'أنقوسة', nameFr: 'Ouled Rechache' },
  { wilayaCode: '40', nameAr: 'عين طوبة', nameFr: 'Aïn Touila' },
  // ── 41 Souk Ahras ─────────────────────────────────────────────────
  { wilayaCode: '41', nameAr: 'سوق أهراس', nameFr: 'Souk Ahras' },
  { wilayaCode: '41', nameAr: 'مداوروش', nameFr: 'Mdaourouch' },
  { wilayaCode: '41', nameAr: 'سدراتة', nameFr: 'Sedrata' },
  { wilayaCode: '41', nameAr: 'الحنانشة', nameFr: 'Hanancha' },
  { wilayaCode: '41', nameAr: 'عين سلطان', nameFr: 'Aïn Soltane' },
  { wilayaCode: '41', nameAr: 'أولاد إدريس', nameFr: 'Ouled Idris' },
  { wilayaCode: '41', nameAr: 'مشروحة', nameFr: 'Mechroha' },
  { wilayaCode: '41', nameAr: 'تاورة', nameFr: 'Taoura' },
  { wilayaCode: '41', nameAr: 'زعرورة', nameFr: 'Safel El Ouiden' },
  { wilayaCode: '41', nameAr: 'الدريعة', nameFr: 'Drea' },
  { wilayaCode: '41', nameAr: 'خميسة', nameFr: 'Kherraza' },
  // ── 42 Tipaza ─────────────────────────────────────────────────────
  { wilayaCode: '42', nameAr: 'تيبازة', nameFr: 'Tipaza' },
  { wilayaCode: '42', nameAr: 'حجوط', nameFr: 'Hadjout' },
  { wilayaCode: '42', nameAr: 'القليعة', nameFr: 'Koléa' },
  { wilayaCode: '42', nameAr: 'بواسماعيل', nameFr: 'Bou Ismail' },
  { wilayaCode: '42', nameAr: 'شرشال', nameFr: 'Cherchell' },
  { wilayaCode: '42', nameAr: 'بني ميلك', nameFr: 'Beni Milleuk' },
  { wilayaCode: '42', nameAr: 'أحمر العين', nameFr: 'Aïn Tagourait' },
  { wilayaCode: '42', nameAr: 'الحمدانية', nameFr: 'Hamdania' },
  { wilayaCode: '42', nameAr: 'سيدي راشد', nameFr: 'Sidi Rached' },
  { wilayaCode: '42', nameAr: 'مناصر', nameFr: 'Menaceur' },
  { wilayaCode: '42', nameAr: 'عين تقدة', nameFr: 'Aïn Tagourait' },
  { wilayaCode: '42', nameAr: 'قوالم', nameFr: 'Gouraya' },
  { wilayaCode: '42', nameAr: 'الدامة', nameFr: 'Damous' },
  { wilayaCode: '42', nameAr: 'خميستي', nameFr: 'Fouka' },
  { wilayaCode: '42', nameAr: 'فوكة', nameFr: 'Fouka' },
  // ── 43 Mila ───────────────────────────────────────────────────────
  { wilayaCode: '43', nameAr: 'ميلة', nameFr: 'Mila' },
  { wilayaCode: '43', nameAr: 'شلغوم العيد', nameFr: 'Chelghoum El Aïd' },
  { wilayaCode: '43', nameAr: 'أحمد راشدي', nameFr: 'Ahmed Rachedi' },
  { wilayaCode: '43', nameAr: 'سيدي خليفة', nameFr: 'Sidi Khelifa' },
  { wilayaCode: '43', nameAr: 'التلاغمة', nameFr: 'Telerghma' },
  { wilayaCode: '43', nameAr: 'أولاد خلوف', nameFr: 'Ouled Khalouf' },
  { wilayaCode: '43', nameAr: 'فرجيوة', nameFr: 'Ferdjioua' },
  { wilayaCode: '43', nameAr: 'روشة', nameFr: 'Rouached' },
  { wilayaCode: '43', nameAr: 'سيدي عمر', nameFr: 'Sidi Merouane' },
  { wilayaCode: '43', nameAr: 'تاجناين', nameFr: 'Tadjenanet' },
  { wilayaCode: '43', nameAr: 'الشيخ راشد', nameFr: 'Benyahia Abderrahmane' },
  { wilayaCode: '43', nameAr: 'عمير وعلي', nameFr: 'Oued Athmania' },
  // ── 44 Aïn Defla ──────────────────────────────────────────────────
  { wilayaCode: '44', nameAr: 'عين الدفلى', nameFr: 'Aïn Defla' },
  { wilayaCode: '44', nameAr: 'مليانة', nameFr: 'Miliana' },
  { wilayaCode: '44', nameAr: 'الروينة', nameFr: 'Rouina' },
  { wilayaCode: '44', nameAr: 'جنداد', nameFr: 'Djendel' },
  { wilayaCode: '44', nameAr: 'بوقلقال', nameFr: 'Boumedfaa' },
  { wilayaCode: '44', nameAr: 'العطاف', nameFr: 'El Attaf' },
  { wilayaCode: '44', nameAr: 'حاسي الدحو', nameFr: 'Hassi El Hadjar' },
  { wilayaCode: '44', nameAr: 'المسير', nameFr: 'El Amra' },
  { wilayaCode: '44', nameAr: 'عين تركي', nameFr: 'Aïn Torki' },
  { wilayaCode: '44', nameAr: 'عين الشهداء', nameFr: 'Ben Allal' },
  { wilayaCode: '44', nameAr: 'خميس الخشنة', nameFr: 'Khemis Miliana' },
  { wilayaCode: '44', nameAr: 'تاشتة', nameFr: 'Taougrite' },
  // ── 45 Naâma ──────────────────────────────────────────────────────
  { wilayaCode: '45', nameAr: 'النعامة', nameFr: 'Naâma' },
  { wilayaCode: '45', nameAr: 'المشرية', nameFr: 'Mecheria' },
  { wilayaCode: '45', nameAr: 'عين الصفراء', nameFr: 'Aïn Sefra' },
  { wilayaCode: '45', nameAr: 'مقرة', nameFr: 'Moghrar' },
  { wilayaCode: '45', nameAr: 'تيوت', nameFr: 'Tiout' },
  { wilayaCode: '45', nameAr: 'مكمن بن عمار', nameFr: 'Makmen Ben Amar' },
  { wilayaCode: '45', nameAr: 'صفيصيفة', nameFr: 'Sfissifa' },
  { wilayaCode: '45', nameAr: 'جنين بورسيس', nameFr: 'Djeniene Bourezg' },
  // ── 46 Aïn Témouchent ─────────────────────────────────────────────
  { wilayaCode: '46', nameAr: 'عين تموشنت', nameFr: 'Aïn Témouchent' },
  { wilayaCode: '46', nameAr: 'واد الصباح', nameFr: 'Oued Sbaa' },
  { wilayaCode: '46', nameAr: 'سيدي صافي', nameFr: 'Sidi Safi' },
  { wilayaCode: '46', nameAr: 'حمام بوحجر', nameFr: 'Hammam Bou Hadjar' },
  { wilayaCode: '46', nameAr: 'سيدي بن عدة', nameFr: 'Sidi Ben Adda' },
  { wilayaCode: '46', nameAr: 'أولاد قواسم', nameFr: 'Ouled Boudjema' },
  { wilayaCode: '46', nameAr: 'بني صاف', nameFr: 'Beni Saf' },
  { wilayaCode: '46', nameAr: 'المالح', nameFr: 'El Malah' },
  { wilayaCode: '46', nameAr: 'أغلال', nameFr: 'Aghlal' },
  { wilayaCode: '46', nameAr: 'الشبيك', nameFr: 'Terga' },
  // ── 47 Ghardaïa ───────────────────────────────────────────────────
  { wilayaCode: '47', nameAr: 'غرداية', nameFr: 'Ghardaïa' },
  { wilayaCode: '47', nameAr: 'متليلي', nameFr: 'Metlili' },
  { wilayaCode: '47', nameAr: 'الغروارة', nameFr: 'El Guerrara' },
  { wilayaCode: '47', nameAr: 'زلفانة', nameFr: 'Zelfana' },
  { wilayaCode: '47', nameAr: 'الأطيام', nameFr: 'El Atteuf' },
  { wilayaCode: '47', nameAr: 'سبعة', nameFr: 'Sebaa' },
  { wilayaCode: '47', nameAr: 'بريان', nameFr: 'Berrian' },
  { wilayaCode: '47', nameAr: 'الضاية بن ضحوة', nameFr: 'Dhayet Ben Dhahoua' },
  // ── 48 Relizane ───────────────────────────────────────────────────
  { wilayaCode: '48', nameAr: 'غليزان', nameFr: 'Relizane' },
  { wilayaCode: '48', nameAr: 'سيدي لخضر', nameFr: 'Sidi Lakhdar' },
  { wilayaCode: '48', nameAr: 'دار بن عبدالله', nameFr: 'Dar Ben Abdellah' },
  { wilayaCode: '48', nameAr: 'جيلالي بن عمار', nameFr: 'Djilali Ben Amar' },
  { wilayaCode: '48', nameAr: 'أمي وسيف', nameFr: 'Ammi Moussa' },
  { wilayaCode: '48', nameAr: 'مازونة', nameFr: 'Mazouna' },
  { wilayaCode: '48', nameAr: 'الزمالة', nameFr: 'Zemala' },
  { wilayaCode: '48', nameAr: 'حمري', nameFr: 'Hmadna' },
  { wilayaCode: '48', nameAr: 'وادي ركش', nameFr: 'Oued Rhiou' },
  { wilayaCode: '48', nameAr: 'الشحانية', nameFr: 'Yellel' },
  { wilayaCode: '48', nameAr: 'المطمر', nameFr: 'Ouled Sidi Mihoub' },
  { wilayaCode: '48', nameAr: 'رمكة', nameFr: 'Ramka' },
  { wilayaCode: '48', nameAr: 'أولاد يحيى', nameFr: 'Ouled Yahia Khelouf' },
  { wilayaCode: '48', nameAr: 'الصومعة', nameFr: 'Souma' },
  // ── 49 Timimoun ───────────────────────────────────────────────────
  { wilayaCode: '49', nameAr: 'تيميمون', nameFr: 'Timimoun' },
  { wilayaCode: '49', nameAr: 'أولف', nameFr: 'Aoulef' },
  { wilayaCode: '49', nameAr: 'شروين', nameFr: 'Charouine' },
  { wilayaCode: '49', nameAr: 'أوقروت', nameFr: 'Ougrout' },
  { wilayaCode: '49', nameAr: 'تيمي', nameFr: 'Timmi' },
  { wilayaCode: '49', nameAr: 'زاوية كنتة', nameFr: 'Zawiya Kounta' },
  { wilayaCode: '49', nameAr: 'أوقدير', nameFr: 'Ouqdir' },
  { wilayaCode: '49', nameAr: 'ميتركان', nameFr: 'Metarfa' },
  { wilayaCode: '49', nameAr: 'دلدول', nameFr: 'Deldoul' },
  // ── 50 Bordj Badji Mokhtar ────────────────────────────────────────
  { wilayaCode: '50', nameAr: 'برج باجي مختار', nameFr: 'Bordj Badji Mokhtar' },
  { wilayaCode: '50', nameAr: 'تيميياوين', nameFr: 'Timiaouine' },
  // ── 51 Ouled Djellal ──────────────────────────────────────────────
  { wilayaCode: '51', nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal' },
  { wilayaCode: '51', nameAr: 'سيدي خالد', nameFr: 'Sidi Khaled' },
  { wilayaCode: '51', nameAr: 'الدوسن', nameFr: 'Doucen' },
  { wilayaCode: '51', nameAr: 'البسباس', nameFr: 'Besbes' },
  { wilayaCode: '51', nameAr: 'مشونش', nameFr: 'Mechouneche' },
  { wilayaCode: '51', nameAr: 'ملاح العروي', nameFr: 'Mlaha' },
  // ── 52 Béni Abbès ─────────────────────────────────────────────────
  { wilayaCode: '52', nameAr: 'بني عباس', nameFr: 'Béni Abbès' },
  { wilayaCode: '52', nameAr: 'إقلي', nameFr: 'Igli' },
  { wilayaCode: '52', nameAr: 'كرزاز', nameFr: 'Kerzaz' },
  { wilayaCode: '52', nameAr: 'تاغيت', nameFr: 'Taghit' },
  { wilayaCode: '52', nameAr: 'بوكايس', nameFr: 'Boukais' },
  { wilayaCode: '52', nameAr: 'ولاد خدير', nameFr: 'Ouled Khedir' },
  // ── 53 In Salah ───────────────────────────────────────────────────
  { wilayaCode: '53', nameAr: 'عين صالح', nameFr: 'In Salah' },
  { wilayaCode: '53', nameAr: 'فوقرت', nameFr: 'Foggaret Ez Zoua' },
  { wilayaCode: '53', nameAr: 'إن قزام', nameFr: 'In Ghar' },
  // ── 54 In Guezzam ─────────────────────────────────────────────────
  { wilayaCode: '54', nameAr: 'عين قزام', nameFr: 'In Guezzam' },
  { wilayaCode: '54', nameAr: 'تين زاواتين', nameFr: 'Tin Zaouatine' },
  // ── 55 Touggourt ──────────────────────────────────────────────────
  { wilayaCode: '55', nameAr: 'تقرت', nameFr: 'Touggourt' },
  { wilayaCode: '55', nameAr: 'المقارين', nameFr: 'El Mekhadma' },
  { wilayaCode: '55', nameAr: 'النزلة', nameFr: 'El Nezla' },
  { wilayaCode: '55', nameAr: 'القرارة', nameFr: 'El Allia' },
  { wilayaCode: '55', nameAr: 'سيدي سليمان', nameFr: 'Sidi Slimane' },
  { wilayaCode: '55', nameAr: 'الزاوية العابدية', nameFr: 'Zaouia El Abidia' },
  { wilayaCode: '55', nameAr: 'تبركانت', nameFr: 'Tebesbest' },
  { wilayaCode: '55', nameAr: 'تماسين', nameFr: 'Temacine' },
  // ── 56 Djanet ─────────────────────────────────────────────────────
  { wilayaCode: '56', nameAr: 'جانت', nameFr: 'Djanet' },
  { wilayaCode: '56', nameAr: 'برج عمر إدريس', nameFr: 'Bordj Omar Driss' },
  // ── 57 El M'Ghair ─────────────────────────────────────────────────
  { wilayaCode: '57', nameAr: 'المغير', nameFr: 'El M\'Ghair' },
  { wilayaCode: '57', nameAr: 'الرباح', nameFr: 'Robbah' },
  { wilayaCode: '57', nameAr: 'سيدي عون', nameFr: 'Sidi Aoun' },
  { wilayaCode: '57', nameAr: 'تندلة', nameFr: 'Tenedla' },
  { wilayaCode: '57', nameAr: 'سطيل', nameFr: 'Sthel' },
  { wilayaCode: '57', nameAr: 'جامعة', nameFr: 'Djamaa' },
  // ── 58 El Meniaa ──────────────────────────────────────────────────
  { wilayaCode: '58', nameAr: 'المنيعة', nameFr: 'El Meniaa' },
  { wilayaCode: '58', nameAr: 'حاسي القارة', nameFr: 'Hassi Gara' },
  { wilayaCode: '58', nameAr: 'حاسي الفحل', nameFr: 'Hassi El Fehal' },
  { wilayaCode: '58', nameAr: 'أولاد سعيد', nameFr: 'Ouled Said' },
]

// Récupère les communes d'une wilaya (par code)
export function getCommunesByWilaya(wilayaCode: string): Commune[] {
  return COMMUNES.filter(c => c.wilayaCode === wilayaCode)
}

// Récupère une wilaya par son code
export function getWilayaByCode(code: string): Wilaya | undefined {
  return WILAYAS.find(w => w.code === code)
}
