version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: boutique_she_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: she
      POSTGRES_PASSWORD: she_local_2026
      POSTGRES_DB: boutique_she
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
